restaurant:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: nj-cynosdbmysql-grp-jbl3ehg9.sql.tencentcdb.com
#    host: localhost
#    port: 3306
    port: 23091
    database: restaurant
    username: root
    password:

    redis:
      host: localhost
      port: 6379
#      password : 123456
#      database: 10  数据源

#阿里云
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id:
    access-key-secret:
    bucket-name: anliannideren

  wechat:
    appid:
    secret:

